# 测试_物品剧本效果
change_stat(item_target, '臂力', 2)
change_stat(item_target, '根骨', 2)
change_stat(item_target, '悟性', 2)
grant_points(item_target, 3)
learn_external(item_target, '罗汉拳', 3)
learn_talent(item_target, '不稳定的六脉神剑')
suggest('测试物品剧情执行完成：[br]臂力、根骨、悟性各 +2[br]自由属性点 +3[br]习得罗汉拳与测试天赋')

# debug_visual_effects
background('地图.竹林')
fade('out', 0.5)
intertitle('[font_size=72]视觉效果指令测试[/font_size][br]黑场与直接显示', 'center', 'instant')
fade('in', 0.5)

intertitle('[color=#8fd3ff]UPPER · 慢速打字机[/color][br]第一行文字[br]第二行文字', 'upper', 'typewriter', 12)
intertitle('[color=#ffd54f]CENTER · 直接显示[/color][br]点击一次即可继续', 'center', 'instant')
intertitle('[color=#9ee6a8]LOWER · 快速打字机[/color][br]首次点击显示全文，再次点击关闭', 'lower', 'typewriter', 72)

intertitle('接下来测试全屏震动', 'center', 'instant')
shake(18, 0.6)

intertitle('接下来测试四种闪屏：[br]white → red → gold → blue', 'center', 'instant')
flash('white', 0.35, 0.85)
flash('red', 0.35, 0.85)
flash('gold', 0.35, 0.85)
flash('blue', 0.35, 0.85)

filter('grayscale', 1, 0.35)
intertitle('滤镜：grayscale', 'lower', 'instant')
filter('sepia', 1, 0.35)
intertitle('滤镜：sepia', 'lower', 'instant')
filter('cold', 1, 0.35)
intertitle('滤镜：cold', 'lower', 'instant')
filter('warm', 1, 0.35)
intertitle('滤镜：warm', 'lower', 'instant')
filter('poison', 1, 0.35)
intertitle('滤镜：poison', 'lower', 'instant')
filter('night', 1, 0.35)
intertitle('滤镜：night', 'lower', 'instant')
clear_filter(0.5)
intertitle('滤镜已清除', 'center', 'instant')

tint('#4a6fa5', 0.45, 0.5)
intertitle('颜色染色：#4a6fa5', 'lower', 'instant')
filter('night', 0.55, 0.4)
intertitle('夜色滤镜与颜色染色同时生效', 'lower', 'instant')
tint('#7d1635cc', 0.4, 0.5)
intertitle('平滑切换染色：#7d1635CC', 'lower', 'instant')
clear_tint(0.4)
clear_filter(0.4)
intertitle('染色与滤镜均已清除', 'center', 'instant')

distort('ripple', 0.8, 0.35)
intertitle('屏幕形变：ripple', 'lower', 'instant')
distort('wave', 0.8, 0.35)
intertitle('屏幕形变：wave', 'lower', 'instant')
distort('heat', 1, 0.35)
intertitle('屏幕形变：heat', 'lower', 'instant')
distort('fisheye', 0.7, 0.35)
intertitle('屏幕形变：fisheye', 'lower', 'instant')
filter('cold', 0.45, 0.35)
intertitle('鱼眼形变与冷色滤镜同时生效', 'lower', 'instant')
clear_distort(0.4)
clear_filter(0.4)
intertitle('屏幕形变与滤镜均已清除', 'center', 'instant')

intertitle('关闭本段文字后等待 1 秒，再播放金色闪屏', 'center', 'instant')
wait(1)
flash('gold', 0.45, 0.9)

fade('out', 0.5)
intertitle('[font_size=72]测试完成[/font_size][br]点击继续返回当前游戏画面', 'center', 'typewriter', 30)
fade('in', 0.5)
